as207960_support/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django_keycloak_auth.urls')),
    path('', include("support.urls"))
]

support/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.views.index, name='index'),
    path('new/', views.views.new_ticket, name='new_ticket'),
    path('tickets/', views.views.tickets, name='tickets'),
    path('tickets/<str:ticket_id>/', views.views.ticket, name='view-ticket'),
    path('tickets/<str:ticket_id>/verify/', views.views.verify_ticket_alt, name='verify-ticket-alt'),
    path('verify_ticket/<str:verification_token>/', views.views.verify_ticket, name='verify_ticket'),
    path('kyc/<str:session_id>/', views.views.do_kyc, name='do-kyc'),

    path('pgp/', views.views.pgp_keys, name='pgp_keys'),
    path('pgp/new/', views.views.new_pgp_key, name='new_pgp_key'),
    path('pgp/make_primary/<str:key_id>/', views.views.make_pgp_key_primary, name='make_pgp_key_primary'),

    path('agent/tickets/', views.admin.open_tickets, name='agent-open-tickets'),
    path('agent/tickets/closed/', views.admin.closed_tickets, name='agent-closed-tickets'),
    path('agent/tickets/answered/', views.admin.answered_tickets, name='agent-answered-tickets'),
    path('agent/tickets/own/', views.admin.own_tickets, name='agent-own-tickets'),

    path('agent/tickets/new/', views.admin.create_ticket, name='agent-create-ticket'),

    path('agent/tickets/<str:ticket_id>/', views.admin.view_ticket, name='agent-view-ticket'),
    path('agent/tickets/<str:ticket_id>/edit/', views.admin.edit_ticket, name='agent-edit-ticket'),
    path('agent/tickets/<str:ticket_id>/claim/', views.admin.claim_ticket, name='agent-claim-ticket'),
    path('agent/tickets/<str:ticket_id>/close/', views.admin.close_ticket, name='agent-close-ticket'),
    path('agent/tickets/<str:ticket_id>/reopen/', views.admin.reopen_ticket, name='agent-reopen-ticket'),
    path('agent/tickets/<str:ticket_id>/block/', views.admin.block_email, name='agent-block-email'),
    path('agent/tickets/<str:ticket_id>/delete/', views.admin.delete_ticket, name='agent-delete-ticket'),
    path('agent/tickets/<str:ticket_id>/assign/', views.admin.assign_ticket, name='agent-assign-ticket'),

    path('webhook/postal/', views.webhooks.postal_webhook),
    path('webhook/stripe/', views.webhooks.stripe_webhook),
]

support/models.py
import secrets
import as207960_utils.models
import django.core.exceptions
import pgpy
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
import lxml.html.clean


class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True, related_name="customer")
    is_agent = models.BooleanField(blank=True, null=False, default=False)
    full_name = models.CharField(max_length=255)
    email = models.EmailField(db_index=True)
    phone = PhoneNumberField(blank=True, null=True)
    phone_ext = models.CharField(max_length=64, blank=True, null=True, verbose_name="Phone extension")
    pushover_user_key = models.CharField(max_length=255, blank=True, null=True)
    emails_blocked = models.BooleanField(blank=True, null=False, default=False)

    def __str__(self):
        return f"{self.full_name} - {self.email}"

    def save(self, *args, **kwargs):
        if self.user:
            self.full_name = f"{self.user.first_name} {self.user.last_name}"
            self.email = self.user.email
        super().save(*args, **kwargs)

    @classmethod
    def get_by_email(cls, email, name=None):
        customer = Customer.objects.filter(email=email).first()
        if customer:
            if name:
                customer.full_name = name
                customer.save()
            return customer
        else:
            customer = Customer.objects.create(email=email, full_name=name)
            return customer


class CustomerPGPKey(models.Model):
    id = as207960_utils.models.TypedUUIDField("support_pgpkey", primary_key=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name="pgp_keys")
    fingerprint = models.CharField(max_length=255, db_index=True)
    pgp_key = models.TextField()
    primary = models.BooleanField(default=False, null=False, blank=True)

    def __str__(self):
        return f"{self.customer} - {self.fingerprint}"

    def as_key(self):
        return pgpy.PGPKey.from_blob(self.pgp_key)[0]


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profile(instance, **_kwargs):
    try:
        instance.customer.save()
    except django.core.exceptions.ObjectDoesNotExist:
        customer = Customer.objects.filter(email=instance.email).first()
        if customer:
            customer.user = instance
            customer.save()
        else:
            Customer.objects.create(user=instance)


@receiver(user_logged_in)
def update_permissions(request, **_kwargs):
    request.user.customer.is_agent = "support.view_ticket" in request.user.get_all_permissions()


def make_ticket_ref():
    while True:
        possible_ref = secrets.token_hex(4).upper()
        try:
            ticket = Ticket.objects.filter(ref=possible_ref).first()
            if not ticket:
                return possible_ref
        except django.db.ProgrammingError:
            return possible_ref


class Ticket(models.Model):
    STATE_OPEN = "O"
    STATE_CLOSED = "C"
    STATES = (
        (STATE_OPEN, "Open"),
        (STATE_CLOSED, "Closed")
    )

    SOURCE_PHONE = "P"
    SOURCE_WEB = "W"
    SOURCE_EMAIL = "E"
    SOURCE_OTHER = "O"
    SOURCE_INTERNAL = "I"
    SOURCES = (
        (SOURCE_PHONE, "Phone"),
        (SOURCE_WEB, "Web"),
        (SOURCE_EMAIL, "Email"),
        (SOURCE_OTHER, "Other"),
        (SOURCE_INTERNAL, "Internal"),
    )

    PRIORITY_LOW = "L"
    PRIORITY_NORMAL = "N"
    PRIORITY_HIGH = "H"
    PRIORITY_EMERGENCY = "E"
    PRIORITIES = (
        (PRIORITY_LOW, "Low"),
        (PRIORITY_NORMAL, "Normal"),
        (PRIORITY_HIGH, "High"),
        (PRIORITY_EMERGENCY, "Emergency"),
    )

    id = as207960_utils.models.TypedUUIDField("support_ticket", primary_key=True)
    ref = models.CharField(max_length=64, db_index=True, default=make_ticket_ref)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    customer_verified = models.BooleanField(blank=True, null=False, default=False)
    verification_token = models.TextField(blank=True, null=True)
    state = models.CharField(max_length=1, choices=STATES, default=STATE_OPEN)
    source = models.CharField(max_length=1, choices=SOURCES, default=SOURCE_OTHER)
    priority = models.CharField(max_length=1, choices=PRIORITIES, default=PRIORITY_NORMAL)
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    due_date = models.DateTimeField(blank=True, null=True)
    subject = models.CharField(max_length=255)
    deleted = models.BooleanField(blank=True, null=False, default=False)

    def first_message(self):
        return self.messages.order_by('date').first()

    def last_message(self):
        return self.messages.order_by('-date').first()

    def last_customer_message(self, exclude_id=None):
        messages = self.messages.filter(type=TicketMessage.TYPE_CUSTOMER).order_by('-date')
        if exclude_id:
            messages = messages.exclude(id=exclude_id)
        return messages.first()

    def last_response(self, exclude_id=None):
        messages = self.messages.filter(type=TicketMessage.TYPE_RESPONSE).order_by('-date')
        if exclude_id:
            messages = messages.exclude(id=exclude_id)
        return messages.first()

    def last_message_id(self, exclude_id=None):
        messages = self.messages.filter(email_message_id__isnull=False).order_by('-date')
        if exclude_id:
            messages = messages.exclude(email_message_id=exclude_id)
        last_message = messages.first()
        if last_message:
            return last_message.email_message_id
        return None

    def message_ids(self, exclude_id=None):
        messages = self.messages.filter(email_message_id__isnull=False).order_by('-date')
        if exclude_id:
            messages = messages.exclude(email_message_id=exclude_id)
        return list(messages.values_list('email_message_id', flat=True))


class TicketMessage(models.Model):
    TYPE_CUSTOMER = "C"
    TYPE_RESPONSE = "R"
    TYPE_NOTE = "N"
    TYPE_SYSTEM = "S"
    TYPE_SYSTEM_RESPONSE = "E"
    TYPES = (
        (TYPE_CUSTOMER, "Customer"),
        (TYPE_RESPONSE, "Response"),
        (TYPE_NOTE, "Note"),
        (TYPE_SYSTEM, "System"),
        (TYPE_SYSTEM_RESPONSE, "System Response"),
    )

    id = as207960_utils.models.TypedUUIDField("support_ticketmessage", primary_key=True)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, related_name='messages')
    type = models.CharField(max_length=1, choices=TYPES)
    date = models.DateTimeField()
    message = models.TextField()
    email_message_id = models.TextField(blank=True, null=True)
    pgp_signed_message = models.BooleanField(default=False, blank=True, null=False)
    pgp_signature_verified = models.BooleanField(default=False, blank=True, null=False)
    pgp_signing_key = models.ForeignKey(CustomerPGPKey, on_delete=models.SET_NULL, blank=True, null=True)

    @property
    def message_safe(self):
        doc = lxml.html.document_fromstring(self.message)
        cleaner = lxml.html.clean.Cleaner(style=True, inline_style=False)
        clean_doc = cleaner.clean_html(doc)
        return lxml.html.tostring(clean_doc).decode()

    class Meta:
        ordering = ['date']


class TicketMessageAttachment(models.Model):
    id = as207960_utils.models.TypedUUIDField("support_ticketattachment", primary_key=True)
    message = models.ForeignKey(TicketMessage, on_delete=models.CASCADE)
    file_name = models.TextField(blank=True, null=True)
    file = models.FileField()


class VerificationSession(models.Model):
    id = as207960_utils.models.TypedUUIDField("support_verificationsession", primary_key=True)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    stripe_session = models.CharField(max_length=255)

support/views/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from .. import forms, models, tasks
import requests
import stripe.identity
import pgpy
from django.core.paginator import Paginator
from django.conf import settings
from django.db.models import Max
from django.contrib.auth.decorators import login_required
from django.core.exceptions import SuspiciousOperation


def index(request):
    return render(request, "support/index.html")


def new_ticket(request):
    if request.method == "POST":
        form = forms.TicketForm(request.POST)
    else:
        form = forms.TicketForm()

    if request.user.is_authenticated:
        form.fields['name'].initial = request.user.customer.full_name
        form.fields['name'].disabled = True
        form.fields['email'].initial = request.user.customer.email
        form.fields['email'].disabled = True
        form.fields['phone'].initial = request.user.customer.phone
        form.fields['phone'].disabled = True
        form.fields['phone_ext'].value = request.user.customer.phone_ext
        form.fields['phone_ext'].disabled = True

    if request.method == "POST":
        if request.user.is_authenticated:
            recaptcha_success = True
        else:
            recaptcha_success = False
            recaptcha_resp = request.POST.get("g-recaptcha-response")
            if not settings.RECAPTCHA_SECRET_KEY:
                recaptcha_success = True
            else:
                if recaptcha_resp:
                    r = requests.post("https://www.google.com/recaptcha/api/siteverify", data={
                        "secret": settings.RECAPTCHA_SECRET_KEY,
                        "response": recaptcha_resp
                    }).json()
                    recaptcha_success = r["success"]

        if recaptcha_success and form.is_valid():
            if request.user.is_authenticated:
                customer = request.user.customer
            else:
                is_valid = True
                customer = models.Customer.objects.filter(email=form.cleaned_data['email']).first()
                if customer:
                    if customer.user and customer.user != request.user:
                        is_valid = False
                        form.add_error('email', "Email already connected to user, please login.")
                else:
                    customer = models.Customer(
                        email=form.cleaned_data['email'],
                    )

                if is_valid:
                    customer.full_name = form.cleaned_data['name']
                    customer.phone = form.cleaned_data['phone']
                    customer.phone_ext = form.cleaned_data['phone_ext']
                    customer.save()

            tasks.open_ticket(
                customer, form.cleaned_data['subject'], form.cleaned_data['message'], models.Ticket.SOURCE_WEB,
                models.Ticket.PRIORITY_NORMAL, verified=request.user.is_authenticated
            )
            return render(request, "support/ticket_opened.html", {
                "ticket_email": customer.email
            })

    return render(request, "support/new_ticket.html", {
        "ticket_form": form
    })


@login_required
def tickets(request):
    user_tickets = models.Ticket.objects.annotate(latest_message=Max('messages__date')) \
        .order_by('-latest_message') \
        .filter(customer=request.user.customer) \
        .distinct()

    tickets = Paginator(user_tickets, 10)

    page_number = request.GET.get('page')
    page_obj = tickets.get_page(page_number)

    return render(request, "support/tickets.html", {
        "tickets": page_obj
    })


@login_required
def ticket(request, ticket_id):
    user_ticket = get_object_or_404(models.Ticket, id=ticket_id)

    if user_ticket.customer != request.user.customer:
        raise SuspiciousOperation()

    if request.method == "POST":
        ticket_reply_form = forms.TicketCustomerReplyForm(request.POST)
        if ticket_reply_form.is_valid() and user_ticket.state != user_ticket.STATE_CLOSED:
            tasks.post_message(user_ticket, ticket_reply_form.cleaned_data['message'])
            return redirect('view-ticket', user_ticket.id)
    else:
        ticket_reply_form = forms.TicketCustomerReplyForm()

    return render(request, "support/ticket.html", {
        "ticket": user_ticket,
        "ticket_reply_form": ticket_reply_form
    })


@login_required
def verify_ticket(request, verification_token):
    user_ticket = get_object_or_404(models.Ticket, verification_token=verification_token)

    user_ticket.customer = request.user.customer
    user_ticket.customer_verified = True
    user_ticket.save()

    return render(request, "support/ticket_verified.html")


@login_required
def verify_ticket_alt(request, ticket_id):
    user_ticket = get_object_or_404(models.Ticket, id=ticket_id)

    if user_ticket.customer != request.user.customer:
        raise SuspiciousOperation()

    if request.method == "POST" and request.POST.get("verify") == "true":
        user_ticket.customer = request.user.customer
        user_ticket.customer_verified = True
        user_ticket.save()
        return redirect('view-ticket', user_ticket.id)

    return render(request, "support/verify_ticket.html", {
        "ticket": user_ticket
    })


def do_kyc(request, session_id):
    verification_session = get_object_or_404(models.VerificationSession, id=session_id)

    stripe_verification_session = stripe.identity.VerificationSession.retrieve(verification_session.stripe_session)

    return redirect(stripe_verification_session.url)


@login_required
def pgp_keys(request):
    keys = models.CustomerPGPKey.objects.filter(customer=request.user.customer)

    return render(request, "support/pgp_keys.html", {
        "keys": keys
    })


@login_required
def new_pgp_key(request):
    if request.method == "POST":
        form = forms.PGPKeyForm(request.POST)
        if form.is_valid():
            try:
                key, _ = pgpy.PGPKey.from_blob(form.cleaned_data['key'])
            except (ValueError, pgpy.errors.PGPError):
                form.add_error('key', "No valid PGP key found")
            else:
                models.CustomerPGPKey.objects.update_or_create(
                    customer=request.user.customer,
                    fingerprint=key.fingerprint,
                    defaults={
                        "pgp_key": str(key),
                        "primary": request.user.customer.pgp_keys.count() == 0,
                    }
                )
                return redirect('pgp_keys')
    else:
        form = forms.PGPKeyForm()

    return render(request, "support/add_pgp_key.html", {
        "form": form
    })


@login_required
@require_POST
def make_pgp_key_primary(request, key_id):
    key = get_object_or_404(models.CustomerPGPKey, id=key_id)
    if request.POST.get("make_pgp_key_primary") == "true" and key.customer == request.user.customer:
        models.CustomerPGPKey.objects.all().update(primary=False)
        key.primary = True
        key.save()

    return redirect('pgp_keys')

support/templates/support/admin/assign_ticket.html
{% extends 'support/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="stripe">
        <div class="container my-5">
            <div class="bg-light p-3 rounded my-4">
                <h1 class="display-4">Assign ticket #{{ ticket.ref }}</h1>
                <h2>{{ ticket.subject }}</h2>
                <hr>
                {% crispy ticket_assign_form ticket_assign_form.helper %}
            </div>
        </div>
    </section>
{% endblock %}

support/templates/support/admin/block_email.html
{% extends 'support/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="stripe">
        <div class="container my-5">
            <div class="bg-light p-3 rounded my-4">
                <h1 class="display-4">Block email</h1>
                <p class="lead"><b>Email:</b> {{ ticket.customer.email }}</p>
                <p>
                    Tickets from this email will be ignored, and they will have to submit tickets using the web interface.
                </p>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="btn-group mt-3">
                        <a href="{% url 'agent-view-ticket' ticket.id %}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" name="block" value="true" class="btn btn-danger">Block</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

support/templates/support/admin/claim_ticket.html
{% extends 'support/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="stripe">
        <div class="container my-5">
            <div class="bg-light p-3 rounded my-4">
                <h1 class="display-4">Claim ticket #{{ ticket.ref }}</h1>
                <h2>{{ ticket.subject }}</h2>
                <hr>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="btn-group">
                        <a href="{% url 'agent-view-ticket' ticket.id %}" class="btn btn-danger">Cancel</a>
                        <button type="submit" name="claim" value="true" class="btn btn-success">Claim</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

support/templates/support/admin/close_ticket.html
{% extends 'support/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="stripe">
        <div class="container my-5">
            <div class="bg-light p-3 rounded my-4">
                <h1 class="display-4">Close ticket #{{ ticket.ref }}</h1>
                <h2>{{ ticket.subject }}</h2>
                <hr>
                {% crispy ticket_close_form ticket_close_form.helper %}
            </div>
        </div>
    </section>
{% endblock %}

support/templates/support/admin/create_ticket.html
{% extends 'support/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="stripe">
        <div class="container my-5">
            <div class="bg-light p-3 rounded my-4">
                <h1 class="display-4">Create new ticket</h1>
                <hr>
                {% crispy ticket_create_form ticket_create_form.helper %}
            </div>
        </div>
    </section>
{% endblock %}

support/templates/support/admin/delete_ticket.html
{% extends 'support/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="stripe">
        <div class="container my-5">
            <div class="bg-light p-3 rounded my-4">
                <h1 class="display-4">Delete ticket #{{ ticket.ref }}</h1>
                <h2>{{ ticket.subject }}</h2>
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="btn-group mt-3">
                        <a href="{% url 'agent-view-ticket' ticket.id %}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" name="delete" value="true" class="btn btn-danger">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

support/templates/support/admin/ticket.html
{% extends 'support/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="stripe">
        <div class="container my-5">
            <div class="bg-light p-3 rounded my-4">
                <h1 class="display-4">Ticket #{{ ticket.ref }}</h1>
                <h2>{{ ticket.subject }}</h2>
                {% if perms.support.change_ticket %}
                    <div class="btn-group">
                        {% if ticket.assigned_to != user %}
                            <a href="{% url 'agent-claim-ticket' ticket.id %}" class="btn btn-success">Claim</a>
                        {% endif %}
                        <a href="{% url 'agent-edit-ticket' ticket.id %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'agent-assign-ticket' ticket.id %}" class="btn btn-secondary">Assign</a>
                        {% if ticket.state == "O" %}
                            <a href="{% url 'agent-close-ticket' ticket.id %}" class="btn btn-danger">Close</a>
                        {% elif ticket.state == "C" %}
                            <a href="{% url 'agent-reopen-ticket' ticket.id %}" class="btn btn-info">Reopen</a>
                        {% endif %}
                        {% if not ticket.customer.emails_blocked %}
                            <a href="{% url 'agent-block-email' ticket.id %}" class="btn btn-danger">Block email</a>
                        {% endif %}
                        <a href="{% url 'agent-delete-ticket' ticket.id %}" class="btn btn-danger">Delete</a>
                    </div>
                {% endif %}
                <div class="row mt-2">
                    <div class="col">
                        <b>Status:</b>
                        {% if ticket.state == "O" %}
                            <span class="badge badge-pill bg-success">Open</span>
                        {% elif ticket.state == "C" %}
                            <span class="badge badge-pill bg-danger">Closed</span>
                        {% else %}
                            {{ ticket.get_state_display }}
                        {% endif %}
                        <br>
                        <b>Priority:</b>
                        {% if ticket.priority == ticket.PRIORITY_LOW %}
                            <span class="badge badge-pill bg-secondary">Low</span>
                        {% elif ticket.priority == ticket.PRIORITY_NORMAL %}
                            <span class="badge badge-pill bg-primary">Normal</span>
                        {% elif ticket.priority == ticket.PRIORITY_HIGH %}
                            <span class="badge badge-pill bg-warning">High</span>
                        {% elif ticket.priority == ticket.PRIORITY_EMERGENCY %}
                            <span class="badge badge-pill bg-danger">Emergency</span>
                        {% else %}
                            {{ ticket.get_priority_display }}
                        {% endif %}
                        <br>
                        <b>Source:</b> {{ ticket.get_source_display }}
                        <br>
                        <b>Assigned to:</b>
                        {% if ticket.assigned_to %}
                            {{ ticket.assigned_to.first_name }} {{ ticket.assigned_to.last_name }}
                        {% else %}
                            N/A
                        {% endif %}
                        <br>
                        <b>Due date:</b>
                        {% if ticket.due_date %}
                            {{ ticket.due_date }}
                        {% else %}
                            N/A
                        {% endif %}
                    </div>
                    <div class="col">
                        <b>Name: </b> {{ ticket.customer.full_name }}
                        {% if ticket.customer_verified %}
                            <span class="badge bg-success">Verified</span>
                        {% else %}
                            <span class="badge bg-danger">Unverified</span>
                        {% endif %}
                        <br>
                        <b>Email:</b> {{ ticket.customer.email }}
                        <br>
                        <b>Phone:</b>
                        {% if ticket.customer.phone %}
                            {{ ticket.customer.phone.as_e164 }}
                            {% if ticket.customer.phone_ext %}ext. {{ ticket.customer.phone_ext }}{% endif %}
                        {% else %}
                            N/A
                        {% endif %}
                        <br>
                        <b>User ID: </b>
                        {% if ticket.customer.user %}{{ ticket.customer.user.username }}{% else %}N/A{% endif %}
                        <br>
                        <b>Last message: </b>
                        {% if ticket.last_customer_message %}{{ ticket.last_customer_message.date }}{% else %}N/A{% endif %}
                        <br>
                        <b>Last response: </b>
                        {% if ticket.last_response %}{{ ticket.last_response.date }}{% else %}N/A{% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="container mt-5">
        <h3>Ticket thread</h3>
        {% for message in ticket.messages.all %}
            <div class="card my-3{% if message.type == "C" %} border-primary{% elif message.type == "R" %} border-success{% elif message.type == "N" %} border-secondary{% elif message.type == "S" or message.type == "E" %} border-warning{% endif %}">
                <div class="card-header">
                    {{ message.date }}
                    - <b>
                        {% if message.type == "C" %}
                            Customer message
                        {% elif message.type == "R" %}
                            Response
                        {% elif message.type == "N" %}
                            Internal note
                        {% elif message.type == "S" or message.type == "E" %}
                            System note
                        {% else %}
                            {{ message.get_type_display }}
                        {% endif %}
                    </b>
                    {% if message.pgp_signed_message %}
                        <br/>
                        PGP signed message.
                        {% if message.pgp_signature_verified %}
                            <b>Message signature verified.</b>
                        {% else %}
                            <b>Signature verification failed.</b>
                        {% endif %}
                        <br/>
                        {% if message.pgp_signing_key %}
                            Signed with key: {{ message.pgp_signing_key.fingerprint }}
                        {% else %}
                            Unknown signing key.
                        {% endif %}
                    {% endif %}
                </div>
                <div class="card-body">
                    {{ message.message_safe|safe }}
                </div>
                {% if message.ticketmessageattachment_set.all %}
                    <ul class="list-group list-group-flush">
                        {% for attachment in message.ticketmessageattachment_set.all %}
                            <li class="list-group-item"><a href="{{ attachment.file.url }}" target="_blank">{{ attachment.file_name }}</a></li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <div class="container my-3">
        <div class="bg-light p-3 rounded my-4">
            <ul class="nav nav-pills" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="reply-tab" data-toggle="tab" href="#reply" role="tab"
                       aria-controls="reply" aria-selected="true">Post reply</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="note-tab" data-toggle="tab" href="#note" role="tab"
                       aria-controls="note" aria-selected="false">Post note</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="kyc-tab" data-toggle="tab" href="#assign" role="tab"
                       aria-controls="assign" aria-selected="false">Request identity verification</a>
                </li>
            </ul>
            <div class="tab-content mt-3">
                <div class="tab-pane fade show active" id="reply" role="tabpanel" aria-labelledby="reply-tab">
                    {% crispy ticket_reply_form ticket_reply_form.helper %}
                </div>
                <div class="tab-pane fade" id="note" role="tabpanel" aria-labelledby="note-tab">
                    {% crispy ticket_note_form ticket_note_form.helper %}
                </div>
                <div class="tab-pane fade" id="assign" role="tabpanel" aria-labelledby="kyc-tab">
                    <p>
                        The user will be sent a link to upload their identity documents.
                    </p>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="btn-group">
                            <button type="submit" name="type" value="kyc" class="btn btn-primary">Send request</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}